import { site } from "@/config/constants";

export default function TermsAndPrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-8">
      <h1 className="mb-4 text-3xl font-bold">Terms of Use</h1>
      <p className="mb-4 italic">Last Updated: October 20, 2024</p>

      <p className="mb-4">
        Please read these Terms of Use (&quot;<strong>Terms</strong>&quot;,
        &quot;
        <strong>Terms of Use</strong>&quot;) carefully before using the
        {site.name} web application (the &quot;<strong>Service</strong>&quot;)
        operated by <strong>{site.name}</strong> (&quot;<strong>us</strong>
        &quot;, &quot;
        <strong>we</strong>
        &quot;, or &quot;<strong>our</strong>&quot;). Your access to and use of
        the Service is conditioned on your acceptance of and compliance with
        these Terms. These Terms apply to all visitors, users, and others who
        access or use the Service.
      </p>

      <p className="mb-4">
        By accessing or using the Service, you agree to be bound by these Terms.
        If you disagree with any part of the terms, you may not access the
        Service.
      </p>

      <hr className="my-8 border-gray-300" />

      <h2 className="mb-4 text-2xl font-semibold">
        1. Purpose and Limitations of the Service
      </h2>
      <p className="mb-4">
        The Service is designed to generate full business plans based on user
        input, leveraging OpenAI APIs. The content provided by the Service is
        intended for <strong>educational purposes only</strong> and should not
        be considered professional business advice. Users should consult with a
        professional advisor before making any decisions based on the content
        generated by the Service.
      </p>

      <hr className="my-8 border-gray-300" />

      <h2 className="mb-4 text-2xl font-semibold">
        2. Ownership of Data and Intellectual Property
      </h2>
      <p className="mb-4">
        All data submitted by users, including but not limited to email
        addresses and startup ideas, remains the property of the respective
        users. <strong>{site.name}</strong> does not claim any ownership rights
        in the data submitted by users.
      </p>

      <hr className="my-8 border-gray-300" />

      <h2 className="mb-4 text-2xl font-semibold">3. Data Privacy and Usage</h2>
      <p className="mb-4">
        We will store user data, including email addresses and startup ideas,
        solely for the purpose of optimizing the Service. We will not use user
        data for any other purposes, nor will we share, sell, or distribute user
        data to any third parties.
      </p>
      <p className="mb-4">
        By using the Service, you agree that we may add your email address to
        our mailing list to notify you of new programs or updates related to our
        Service. You may unsubscribe from these communications at any time.
      </p>

      <hr className="my-8 border-gray-300" />

      <h2 className="mb-4 text-2xl font-semibold">
        4. Disclaimer of Warranties
      </h2>
      <p className="mb-4">
        The Service is provided on an &quot;<strong>as is</strong>&quot; and
        &quot;
        <strong>as available</strong>&quot; basis. <strong>{site.name}</strong>{" "}
        makes no warranties, express or implied, regarding the accuracy,
        reliability, or completeness of the content generated by the Service. We
        expressly disclaim any warranties of merchantability, fitness for a
        particular purpose, or non-infringement.
      </p>

      <hr className="my-8 border-gray-300" />

      <h2 className="mb-4 text-2xl font-semibold">
        5. Limitation of Liability
      </h2>
      <p className="mb-4">
        In no event shall <strong>{site.name}</strong>, its officers, directors,
        employees, or affiliates be liable for any indirect, incidental,
        special, consequential, or punitive damages—including but not limited to
        loss of profits, data, or use—whether in an action in contract, tort
        (including negligence), or otherwise, arising out of or in connection
        with your access to or use of the Service.
      </p>

      <hr className="my-8 border-gray-300" />

      <h2 className="mb-4 text-2xl font-semibold">
        6. Changes to Terms of Use
      </h2>
      <p className="mb-4">
        We reserve the right, at our sole discretion, to modify or replace these
        Terms at any time. Any changes will be effective immediately upon
        posting the revised Terms on the Service. By continuing to access or use
        our Service after those revisions become effective, you agree to be
        bound by the revised Terms. If you do not agree to the new Terms, please
        stop using the Service.
      </p>

      <hr className="my-8 border-gray-300" />

      <h2 className="mb-4 text-2xl font-semibold">7. Governing Law</h2>
      <p className="mb-4">
        These Terms shall be governed and construed in accordance with the laws
        of the <strong>Portugal</strong>, without regard to its conflict of law
        provisions.
      </p>

      <hr className="my-8 border-gray-300" />

      <h2 className="mb-4 text-2xl font-semibold">8. Contact Us</h2>
      <p className="mb-4">
        If you have any questions about these Terms, please contact us:
      </p>
      <ul className="mb-4 list-disc pl-8">
        <li>
          <strong>By Email:</strong> {site.links.supportEmail}
        </li>
      </ul>

      <hr className="my-8 border-gray-300" />

      <p className="text-sm italic">
        <strong>Disclaimer:</strong> This Terms of Use document is provided for
        general informational purposes and may not be fully compliant with all
        applicable laws and regulations in your jurisdiction. We recommend
        consulting with a legal professional to ensure that your Terms of Use
        comply with all relevant laws and regulations.
      </p>
    </div>
  );
}
